"""Episteme package."""

from .candidate_assessment import CandidateConstraintAssessment, CandidateConstraintStatus
from .ingest import ingest_jsonl, ingest_jsonl_file
from .model import (
    AssessmentTargetKind,
    DiscoveryExpectation,
    DiscoveryExpectationKind,
    DiscoveryFinding,
    DiscoveryFindingKind,
    DiscoveryMeasure,
    StructuralPressureComponent,
    KnowledgeStateConsequence,
    KnowledgeStateConsequenceKind,
    KnowledgeStateTargetKind,
    EvidenceAssessment,
    Review,
    ReviewTargetKind,
    ReviewDisposition,
    Hypothesis,
    Model,
    Prediction,
    PredictionEvaluation,
    PredictionEvaluationOutcome,
    ExperimentProposal,
    LifecycleEvent,
    LifecycleEventKind,
    SCHEMA_VERSION,
    Provenance,
    Record,
    RecordKind,
    Relationship,
    Transformation,
    canonical_json,
    make_record,
    make_relationship,
)
from .discovery import detect_accounting_gap, detect_constraint_gap, detect_positional_gap, detect_expected_gap, detect_structural_payload_sequence_gap, detect_structural_sequence_gap, discover_competing_prediction_opportunities, discover_evaluation_tensions, discover_explicit_contradictions, question_from_finding
from .store import Store
from .trail import DiscoveryTrail, TrailEntry, build_discovery_trail
from .proposals import complete_structural_gap, predict, propose_candidate_discrimination_experiment, propose_discriminating_prediction, propose_experiment, propose_hypothesis, represent_model
from .public import (discovery_lineage, discovery_report, discovery_trail, get_record, get_discovery_finding, list_discovery_findings, list_records, get_hypothesis, list_hypotheses, get_model, list_models, get_prediction, list_predictions, get_experiment_proposal, list_experiment_proposals, get_prediction_evaluation, list_prediction_evaluations, get_knowledge_state_consequence, list_knowledge_state_consequences, get_review, list_reviews, get_relationship, list_relationships, get_workflow_definition, list_workflow_definitions, get_workflow_execution, list_workflow_executions, workflow_execution_lineage, list_workflow_executions_for_artifact)
from .html import render_discovery_report_html
from .public_import import import_crossref_works
from .orchestration import WorkflowDefinition, WorkflowExecution, WorkflowStep, WorkflowStepResult, run_workflow

__version__ = "0.1.0"

__all__ = [
    "SCHEMA_VERSION",
    "CandidateConstraintAssessment",
    "CandidateConstraintStatus",
    "AssessmentTargetKind",
    "DiscoveryExpectation",
    "DiscoveryExpectationKind",
    "DiscoveryFinding",
    "DiscoveryFindingKind",
    "DiscoveryMeasure",
    "StructuralPressureComponent",
    "KnowledgeStateConsequence",
    "KnowledgeStateConsequenceKind",
    "KnowledgeStateTargetKind",
    "EvidenceAssessment",
    "Review",
    "ReviewTargetKind",
    "ReviewDisposition",
    "Hypothesis",
    "Model",
    "Prediction",
    "PredictionEvaluation",
    "PredictionEvaluationOutcome",
    "ExperimentProposal",
    "LifecycleEvent",
    "LifecycleEventKind",
    "Provenance",
    "Record",
    "RecordKind",
    "Relationship",
    "Transformation",
    "Store",
    "DiscoveryTrail",
    "TrailEntry",
    "build_discovery_trail",
    "canonical_json",
    "make_record",
    "make_relationship",
    "detect_accounting_gap",
    "detect_constraint_gap",
    "detect_positional_gap",
    "detect_expected_gap",
    "detect_structural_sequence_gap",
    "detect_structural_payload_sequence_gap",
    "discover_competing_prediction_opportunities",
    "discover_evaluation_tensions",
    "discover_explicit_contradictions",
    "question_from_finding",
    "ingest_jsonl",
    "ingest_jsonl_file",
    "complete_structural_gap",
    "propose_candidate_discrimination_experiment",
    "propose_discriminating_prediction",
    "propose_hypothesis",
    "represent_model",
    "predict",
    "propose_experiment",
    "get_record",
    "get_discovery_finding",
    "list_discovery_findings",
    "get_hypothesis",
    "list_hypotheses",
    "get_model",
    "list_models",
    "get_prediction",
    "list_predictions",
    "get_experiment_proposal",
    "list_experiment_proposals",
    "get_prediction_evaluation",
    "list_prediction_evaluations",
    "get_knowledge_state_consequence",
    "list_knowledge_state_consequences",
    "get_review",
    "get_relationship",
    "list_relationships",
    "get_workflow_definition",
    "list_workflow_definitions",
    "get_workflow_execution",
    "list_workflow_executions",
    "workflow_execution_lineage",
    "list_workflow_executions_for_artifact",
    "list_reviews",
    "list_records",
    "discovery_trail",
    "discovery_lineage",
    "discovery_report",
    "render_discovery_report_html",
    "import_crossref_works",
    "WorkflowDefinition",
    "WorkflowExecution",
    "WorkflowStep",
    "WorkflowStepResult",
    "run_workflow",
]
