"""Episteme package."""

from .ingest import ingest_jsonl, ingest_jsonl_file
from .model import (
    AssessmentTargetKind,
    DiscoveryFinding,
    DiscoveryFindingKind,
    DiscoveryMeasure,
    KnowledgeStateConsequence,
    KnowledgeStateConsequenceKind,
    KnowledgeStateTargetKind,
    EvidenceAssessment,
    Review,
    ReviewTargetKind,
    ReviewDisposition,
    Hypothesis,
    Model,
    Prediction,
    PredictionEvaluation,
    PredictionEvaluationOutcome,
    ExperimentProposal,
    LifecycleEvent,
    LifecycleEventKind,
    SCHEMA_VERSION,
    Provenance,
    Record,
    RecordKind,
    Relationship,
    Transformation,
    canonical_json,
    make_record,
    make_relationship,
)
from .discovery import detect_expected_gap, discover_evaluation_tensions, discover_explicit_contradictions, question_from_finding
from .store import Store
from .trail import DiscoveryTrail, TrailEntry, build_discovery_trail
from .proposals import predict, propose_experiment, propose_hypothesis, represent_model
from .public import discovery_lineage, discovery_report, discovery_trail, get_record, list_records
from .html import render_discovery_report_html
from .public_import import import_crossref_works

__version__ = "0.1.0"

__all__ = [
    "SCHEMA_VERSION",
    "AssessmentTargetKind",
    "DiscoveryFinding",
    "DiscoveryFindingKind",
    "DiscoveryMeasure",
    "KnowledgeStateConsequence",
    "KnowledgeStateConsequenceKind",
    "KnowledgeStateTargetKind",
    "EvidenceAssessment",
    "Review",
    "ReviewTargetKind",
    "ReviewDisposition",
    "Hypothesis",
    "Model",
    "Prediction",
    "PredictionEvaluation",
    "PredictionEvaluationOutcome",
    "ExperimentProposal",
    "LifecycleEvent",
    "LifecycleEventKind",
    "Provenance",
    "Record",
    "RecordKind",
    "Relationship",
    "Transformation",
    "Store",
    "DiscoveryTrail",
    "TrailEntry",
    "build_discovery_trail",
    "canonical_json",
    "make_record",
    "make_relationship",
    "detect_expected_gap",
    "discover_evaluation_tensions",
    "discover_explicit_contradictions",
    "question_from_finding",
    "ingest_jsonl",
    "ingest_jsonl_file",
    "propose_hypothesis",
    "represent_model",
    "predict",
    "propose_experiment",
    "get_record",
    "list_records",
    "discovery_trail",
    "discovery_lineage",
    "discovery_report",
    "render_discovery_report_html",
    "import_crossref_works",
]
